---
application:
    name: 'camogeneics-backend'
    project: 'APIs'
    organization: 'QoveryCommunity'
routers:
    - name: 'main-camogeneics-backend'
      routes:
          - application_name: 'camogeneics-backend'
            paths:
                - '/*'
